// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: app/log/command/config.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace V2Ray.Core.App.Log.Command {
  public static partial class LoggerService
  {
    static readonly string __ServiceName = "v2ray.core.app.log.command.LoggerService";

    static readonly grpc::Marshaller<global::V2Ray.Core.App.Log.Command.RestartLoggerRequest> __Marshaller_v2ray_core_app_log_command_RestartLoggerRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::V2Ray.Core.App.Log.Command.RestartLoggerRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::V2Ray.Core.App.Log.Command.RestartLoggerResponse> __Marshaller_v2ray_core_app_log_command_RestartLoggerResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::V2Ray.Core.App.Log.Command.RestartLoggerResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::V2Ray.Core.App.Log.Command.RestartLoggerRequest, global::V2Ray.Core.App.Log.Command.RestartLoggerResponse> __Method_RestartLogger = new grpc::Method<global::V2Ray.Core.App.Log.Command.RestartLoggerRequest, global::V2Ray.Core.App.Log.Command.RestartLoggerResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RestartLogger",
        __Marshaller_v2ray_core_app_log_command_RestartLoggerRequest,
        __Marshaller_v2ray_core_app_log_command_RestartLoggerResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::V2Ray.Core.App.Log.Command.ConfigReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LoggerService</summary>
    [grpc::BindServiceMethod(typeof(LoggerService), "BindService")]
    public abstract partial class LoggerServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::V2Ray.Core.App.Log.Command.RestartLoggerResponse> RestartLogger(global::V2Ray.Core.App.Log.Command.RestartLoggerRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LoggerService</summary>
    public partial class LoggerServiceClient : grpc::ClientBase<LoggerServiceClient>
    {
      /// <summary>Creates a new client for LoggerService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LoggerServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LoggerService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LoggerServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LoggerServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LoggerServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::V2Ray.Core.App.Log.Command.RestartLoggerResponse RestartLogger(global::V2Ray.Core.App.Log.Command.RestartLoggerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartLogger(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::V2Ray.Core.App.Log.Command.RestartLoggerResponse RestartLogger(global::V2Ray.Core.App.Log.Command.RestartLoggerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RestartLogger, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::V2Ray.Core.App.Log.Command.RestartLoggerResponse> RestartLoggerAsync(global::V2Ray.Core.App.Log.Command.RestartLoggerRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RestartLoggerAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::V2Ray.Core.App.Log.Command.RestartLoggerResponse> RestartLoggerAsync(global::V2Ray.Core.App.Log.Command.RestartLoggerRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RestartLogger, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LoggerServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LoggerServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LoggerServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RestartLogger, serviceImpl.RestartLogger).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LoggerServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RestartLogger, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::V2Ray.Core.App.Log.Command.RestartLoggerRequest, global::V2Ray.Core.App.Log.Command.RestartLoggerResponse>(serviceImpl.RestartLogger));
    }

  }
}
#endregion
