// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: common/log/log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace V2Ray.Core.Common.Log {

  /// <summary>Holder for reflection information generated from common/log/log.proto</summary>
  public static partial class LogReflection {

    #region Descriptor
    /// <summary>File descriptor for common/log/log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRjb21tb24vbG9nL2xvZy5wcm90bxIVdjJyYXkuY29yZS5jb21tb24ubG9n",
            "KkQKCFNldmVyaXR5EgsKB1Vua25vd24QABIJCgVFcnJvchABEgsKB1dhcm5p",
            "bmcQAhIICgRJbmZvEAMSCQoFRGVidWcQBEI6Chljb20udjJyYXkuY29yZS5j",
            "b21tb24ubG9nUAFaA2xvZ6oCFVYyUmF5LkNvcmUuQ29tbW9uLkxvZ2IGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::V2Ray.Core.Common.Log.Severity), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Severity {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Error")] Error = 1,
    [pbr::OriginalName("Warning")] Warning = 2,
    [pbr::OriginalName("Info")] Info = 3,
    [pbr::OriginalName("Debug")] Debug = 4,
  }

  #endregion

}

#endregion Designer generated code
